name: Build and Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.25

      - name: Build
        run: make build-grid

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/boring-*.tar.gz
          file_glob: true
          tag: ${{ github.ref }}
          body: "Automatic build release for version ${{ github.ref_name }}"
          draft: true
