name: Test and Cover
on:
  push:
    branches: [main, develop]
  pull_request:
  workflow_dispatch:

jobs:
  test-and-cover:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Run tests with coverage
        run: make cover

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: cover_lines.out
          format: golang